# Assignment 1
by [Jay Nakum](https://JayNakum.github.io/) [20BCP304D]

In [2]:
import numpy as np

Q1) WAP to take 10 inputs from the user as comma seperated and stored into a 5*2 matrix.

In [7]:
# numbers = (input('Enter 10 comma seperated numbers: ')).split(',', 9)
numbers = ('1, 2, 3, 4, 5, 6, 7, 8, 9, 10').split(',', 9)
solution = np.array([numbers[:5], numbers[5:]], int)
print(solution)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Q2) WAP to create 4*5 matrix and reverse the elements of 3rd row only.

In [35]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
matrix[2] = matrix[2, ::-1]
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [12 11 10  9]
 [13 14 15 16]
 [17 18 19 20]]


Q3) WAP to create 4*5 matrix and reverse the elements of 2nd column only.

In [36]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
matrix[::, 1] = matrix[::-1, 1]
print(matrix)

[[ 1 18  3  4]
 [ 5 14  7  8]
 [ 9 10 11 12]
 [13  6 15 16]
 [17  2 19 20]]


Q4) Write a NumPy program to test wheather each element of a 1-D array is also present in second array.

In [41]:
arrayA = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arrayB = np.array([2, 4, 6, 8, 10])

if(np.all(np.isin(arrayB, arrayA))):
    print('All elements of arrayB are present in arrayA')

All elements of arrayB are present in arrayA


Q5) Write a NumPy program to find common values between two arrays.

In [43]:
arrayA = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arrayB = np.array([1, 12, 3, 14, 5, 16])
print(np.intersect1d(arrayA, arrayB))

[1 3 5]


Q6) Take two 1-D array and make a new 1D array where all elements are greater than 5.

In [61]:
arrayA = np.array([2, 4, 6, 7, 5, 8, 3, 9, 1, 10])
arrayB = np.array([1, 12, 3, 14, 5, 16])
solution = np.array([x for x in arrayA if x > 5] + [x for x in arrayB if x > 5])
print(solution)

[ 6  7  8  9 10 12 14 16]


Q7) Task

In [63]:
numbers = '1 2 3 4 -8 -10'
values = np.array(numbers.split(), float)
print(values[::-1])

[-10.  -8.   4.   3.   2.   1.]


Q8) Task

In [3]:
sampleInput = '''4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4'''

sampleInput = sampleInput.splitlines()
n,m,p=map(int, sampleInput[0].split())

sampleInput = sampleInput[1:]

arrayA=np.array([sampleInput[i].split() for i in range(n)], int)
arrayB=np.array([sampleInput[i].split() for i in range(n, n + m)], int)

print(np.concatenate((arrayA, arrayB), axis=0))

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
