# NumPy

In [2]:
import numpy as np

How to create an array

In [87]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr1)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Different properties of array

In [6]:
# Dimentions
print(arr1.ndim)
print(arr2.ndim)

1
2


In [7]:
# size
print(arr2.size)

9


In [8]:
# shape (3 x 3)
arr2.shape

(3, 3)

In [9]:
# type of array
type(arr2)

numpy.ndarray

In [10]:
# type of data stored in array
arr2.dtype

dtype('int32')

In [12]:
arr3 = np.array([1, 2, 3, 4, 5, 6.5, 'jay'])
print(arr3)
print(arr3.dtype)

['1' '2' '3' '4' '5' '6.5' 'jay']
<U32


Access elements

In [20]:
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
arr2[-1][-1]

9

In [23]:
arr2[0]

array([1, 2, 3])

In [28]:
print("%s is the first row"%arr2[0])

[1 2 3] is the first row


Change type of array

In [29]:
arr1.astype('float')

array([1., 2., 3., 4., 5.])

In [31]:
arr1 = arr1.astype('str')

In [92]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]], dtype='bool')
arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

Update value in array

In [13]:
arr3[3] = 'Pandit Deendayal Energy University'
print(arr3)

['1' '2' '3' 'Pandit Deendayal Energy Universi' '5' '6.5' 'jay']


In [80]:
arr2[0] = -1, 2, 3
print(arr2)

[[-1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [88]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2[:, 0::2] = 10
print(arr2)

[[10  2 10]
 [10  5 10]
 [10  8 10]]


In [19]:
arr5 = np.array([1, 2, 3 ,4 ,5])
arr5[0] = '10'
print(arr5)
print(arr5.dtype)

[10  2  3  4  5]
int32


String operation in array

In [18]:
arr4 = np.array(['a', 2, 'b', 'c', 'd', 'pdpu'])
arr4[3] = 'Data Mining Lab'
print(arr4)
print(arr4.dtype)

['a' '2' 'b' 'Data Mining' 'd' 'pdpu']
<U11


slicing

In [36]:
# arr1[start:end:step]
print(arr1[1:7])
# arr2[start:end:step, start:end:step]
print(arr2[1:2, 0:2])

['2' '3' '4' '5']
[[4 5]]


In [47]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr1[-4:]

array([6, 7, 8, 9])

In [53]:
arr2[::2, ::2]

array([[1, 3],
       [7, 9]])

In [54]:
arr2[::, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [67]:
arr2[::,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [73]:
arr2[:, 0]

array([1, 4, 7])

In [74]:
arr2[0, :]

array([1, 2, 3])